.env.dev
.env.staging
package.json
src/apollo.ts
src/main.ts
yarn.lock

Using [Apollo](https://v4.apollo.vuejs.org/) for performing GQL operations to the API

GQL - Apollo Client

---

package.json
src/assets/scss/nav.scss
src/components/Nav.vue
src/i18n/i18n.ts
src/i18n/lang/en_US.ts
src/i18n/lang/fr_FR.ts
src/main.ts
src/views/404.vue
src/views/EmotePage/EmoteInteractions.vue
src/views/EmotePage/EmotePage.vue
src/views/Home.vue
yarn.lock

Adding support for locales and translating the app to other languages

Localization - i18n

---

src/assets/scss/components/form/checkbox.scss
src/assets/scss/components/form/radio.scss
src/assets/scss/components/form/text-input.scss
src/components/form/Checkbox.vue
src/components/form/Radio.vue
src/components/form/TextInput.vue
src/views/Admin/AdminUsers.vue

Creating reusable form components

Form Controls

---

src/App.vue
src/assets/scss/components/emote-card.scss
src/assets/scss/default.scss
src/components/overlay/ContextMenu.vue
src/components/utility/EmoteCard.vue
src/components/utility/EmoteCardContext.vue
src/directives/ClickOutside.ts

Creating a re-usable self-positioning context menu utility that can be passed any component

Context Menu

---

locale/en_US.ts
src/assets/gql/users/connection.ts
src/assets/gql/users/user.ts
src/assets/scss/user-page/user-details.scss
src/components/Nav.vue
src/components/modal/ModalConnectionEditor.vue
src/structures/User.ts
src/views/UserPage/UserDetails.vue

Adding interfaces which allow users to add or remove linked accounts

User Connections Editor

---

locale/en_US.ts
src/assets/gql/mutation/EditReport.ts
src/assets/gql/reports/report.ts
src/assets/scss/admin/admin-reports.scss
src/components/utility/ReportForm.vue
src/i18n/index.ts
src/router/index.ts
src/structures/Report.ts
src/views/Admin/AdminReportEditor.vue
src/views/Admin/AdminReports.vue
src/views/EmotePage/EmoteInteractions.vue
src/views/Inbox/InboxMessage.vue

Adding / updating user interfaces for creating and managing reports

Reporting UI & Admin Area

---

src/assets/scss/emotes.scss
src/views/EmoteList/EmoteList.vue

Adding query string params to make paginating through the emote list persist through refreshes and history pushes

Emote List: Persistent Pagination

---

.env.dev
.env.production
.env.staging
locale/en_US.ts
package.json
src/assets/gql/mutation/UserEditors.ts
src/assets/gql/users/user.ts
src/assets/scss/user-page/user-details.scss
src/assets/scss/user-page/user-page.scss
src/components/activity/Activity.vue
src/components/modal/ModalBase.vue
src/components/utility/Icon.vue
src/components/utility/UserQuickSearch.vue
src/icons.ts
src/store/actor.ts
src/store/main.ts
src/store/mutation.ts
src/structures/User.ts
src/views/UserPage/UserDetails.vue
src/views/UserPage/UserEditorModal.vue
src/views/UserPage/UserPage.vue

Building UI components for managing editors

Editor Management UI

---

locale/en_US.ts
package-lock.json
package.json
src/App.vue
src/assets/scss/emote-page/emote-page.scss
src/assets/scss/emotes.scss
src/components/base/LogoAVIF.vue
src/components/utility/EmoteCard.vue
src/components/utility/EmoteMention.vue
src/components/utility/EmoteSetCard.vue
src/store/actor.ts
src/structures/Common.ts
src/structures/Emote.ts
src/views/EmoteList/EmoteList.vue
src/views/EmoteList/Paginator.vue
src/views/EmotePage/EmotePage.vue
src/views/EmotePage/EmoteVersions.vue
src/views/EmoteUpload/EmoteUpload.vue
src/views/Store/SubStatus.vue
src/views/Store/egvault.ts
src/views/UserSettings/UserSettings.vue
yarn.lock

Experiment defaulting all emote images to AVIF for Chrome 100+ users

Trial AV1 Image File Format (AVIF)

---

locale/en_US.ts
src/assets/gql/emotes/emote.ts
src/components/activity/Activity.vue
src/components/activity/EmoteActivity.vue
src/components/form/Checkbox.vue
src/components/form/TextInput.vue
src/icons.ts
src/structures/Common.ts
src/views/EmotePage/EmoteInteractions.vue
src/views/EmotePage/EmotePropertiesModal.vue
src/views/EmoteUpload/EmoteUpload.vue

Adding UI for managing emote properties, such as changing the name, private or zero-width status of an emote

Emote Properties

---

locale/en_US.ts
src/assets/scss/components/form/checkbox.scss
src/assets/scss/emotes.scss
src/components/form/Checkbox.vue
src/components/modal/SelectEmoteSet/SelectEmoteSet.vue
src/components/modal/SelectEmoteSet/SelectEmoteSetContext.vue
src/components/utility/EmoteCard.vue
src/icons.ts
src/store/actor.ts
src/views/EmoteList/EmoteList.vue
src/views/EmoteList/EmoteListUtilBar.vue
src/views/EmoteSetPage/EmoteSetPage.vue

Making some small improvements to the usability of the site

Search Filters & List Set Selection

---

src/components/utility/LoginButton.vue
src/components/utility/LoginButtonPlaform.vue
src/views/UserPage/UserDetails.vue

Preparing for the release of youtube oauth

YouTube Auth

---

src/components/utility/EmoteCard.vue
src/components/utility/EmoteCardList.vue
src/composable/calculate-sized-rows.ts
src/router/users.route.ts
src/views/EmoteList/EmoteList.vue
src/views/EmotePage/EmotePreviews.vue
src/views/EmoteSetPage/EmoteSetPage.vue
src/views/UserPage/UserPage.vue

Only displaying images when they're visible on screen, and reducing the volume of emote cards displayed on the main page

Optimize display of images

---

.env.dev
.env.production
.env.staging
src/App.vue
src/Logger.ts
src/components/utility/EmoteCard.vue
src/composable/object-sub.ts
src/composable/worker.ts
src/worker/Worker.ts
tsconfig.json

Preparing for the removal of the websocket service inside the GQL API

Use EventAPI instead of GraphQL Subscriptions

---

src/components/Nav.vue
src/views/store/StoreHeading.vue
src/views/store/StorePurchase.vue
src/views/store/SubStatus.vue

Christmas Event Ad

---

locale/en_US.ts
src/components/utility/EmoteCard.vue
src/components/utility/EmoteCardContext.vue

no extra space , no issues in this PR

added copy emote feature

---

src/composables/useDownloadLink.ts
src/views/home/HomeDownloads.vue

**Before:                          After:**

Added Download Button for Firefox Beta

---

src/apollo/query/mod-queue.query.ts
src/components/utility/EmoteCard.vue
src/structures/Message.ts
src/views/admin/ModQueue/ModRequestCard.vue

if mods see this they must cum now

ModQ: Display country flag of uploader

---

src/apollo/apollo.ts

Revert "apollo: omit `Authorization` header"

---

src/views/OAuth2.vue

this adds a handler for manual auth

Manual Auth Callback

---

src/components/base/Badge.vue
src/components/utility/BadgeDefs.ts
src/views/emote-set/EmoteSetPage.vue
src/views/store/AnnotatedBadge.vue

Year 2 Sub Badges
